# Generated by Django 5.0.4 on 2024-08-17 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ambiente', '0001_initial'),
        ('Muestra', '0001_initial'),
        ('Precio', '0001_initial'),
        ('TipoServicio', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ambiente.ambiente')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Muestra.muestra')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Precio.precio')),
                ('tiposervicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoServicio.tiposervicio')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios')),
            ],
        ),
    ]
