# Generated by Django 5.0.4 on 2024-10-07 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ambiente', '0001_initial'),
        ('Muestra', '0001_initial'),
        ('TipoServicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_salida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en proceso', 'En Proceso'), ('terminado', 'Terminado')], default='en proceso', max_length=11)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ambiente.ambiente')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Muestra.muestra')),
                ('tiposervicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoServicio.tiposervicio')),
            ],
        ),
    ]
