# Generated by Django 5.0.4 on 2024-08-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ambiente', models.CharField(max_length=45)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
