# Generated by Django 5.1 on 2024-08-12 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ambiente', models.CharField(max_length=45)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=45)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entrada', models.FloatField()),
                ('fecha_entrada', models.DateField()),
                ('fecha_muestra', models.DateField()),
                ('codigo_muestra', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_municipio', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=45)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tiposervicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_finca', models.CharField(max_length=50)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_precio', models.CharField(max_length=45)),
                ('presentacion', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
                ('tiposervicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField()),
                ('codigo_documentos', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_fimision', models.DateField()),
                ('logos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.logos')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipodocumento')),
                ('tiposervicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('contrasena', models.CharField(max_length=45)),
                ('numero_documento', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rol')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambiente')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.muestra')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.precio')),
                ('tiposervicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposervicio')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios'),
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=45)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicio')),
                ('variables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.variables')),
            ],
        ),
        migrations.CreateModel(
            name='Versiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=45)),
                ('estado', models.BooleanField()),
                ('fecha_version', models.DateTimeField()),
                ('documentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.documentos')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='variables',
            name='versiones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.versiones'),
        ),
    ]
