# Generated by Django 5.0.4 on 2024-08-17 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Servicio', '0001_initial'),
        ('Variables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=45)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio.servicio')),
                ('variables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Variables.variables')),
            ],
        ),
    ]
