# Generated by Django 5.0.4 on 2024-09-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documentos', '0001_initial'),
        ('Logos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos_iddocumentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.documentos')),
                ('logo_idlogos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logos.logos')),
            ],
        ),
    ]
