# Generated by Django 5.0.4 on 2024-10-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_dato', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=10)),
                ('unidad_medida', models.CharField(choices=[('Lb', 'Libra'), ('Kg', 'Kilogramo')], default='Lb', max_length=2)),
            ],
        ),
    ]
