# Generated by Django 5.0.4 on 2024-08-17 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Versiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('versiones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Versiones.versiones')),
            ],
        ),
    ]
