# Generated by Django 5.0.4 on 2024-09-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=128)),
                ('tipo_documento', models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ti', 'Tarjeta de Identidad'), ('nit', 'NIT'), ('pasaporte', 'Pasaporte')], default='cc', max_length=10)),
                ('numero_documento', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rol.rol')),
            ],
        ),
    ]
