# Generated by Django 5.0.4 on 2024-09-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=True)),
                ('nombre_documento', models.CharField(max_length=15)),
                ('fecha_version', models.DateTimeField()),
                ('documentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.documentos')),
            ],
        ),
    ]
