# Generated by Django 5.0.4 on 2024-10-07 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoServicio', '0001_initial'),
        ('tipoDocumento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_carga', models.DateField()),
                ('codigo_documentos', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
                ('entrada_salida', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], default='entrada', max_length=7)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoDocumento.tipodocumento')),
                ('tiposervicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoServicio.tiposervicio')),
            ],
        ),
    ]
