# Generated by Django 5.0.4 on 2024-08-17 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoServicio', '0001_initial'),
        ('tipoDocumento', '0002_delete_ambiente_remove_documentos_logos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField()),
                ('codigo_documentos', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_fimision', models.DateField()),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoDocumento.tipodocumento')),
                ('tiposervicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoServicio.tiposervicio')),
            ],
        ),
    ]
