# Generated by Django 5.0.4 on 2024-10-07 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Variables', '0001_initial'),
        ('Versiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_idVariable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Variables.variables')),
                ('fk_id_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Versiones.versiones')),
            ],
        ),
    ]
